### ISSUE TITLE
Packages / docker not being installed

### ISSUE THREAD

**Issue by rvenugopal** [swarmlet/swarmlet#120]
Hello

I just tried an installation on a digital ocean server and looks like the installation is incomplete. As per the docs docker also should have been installed.  I tried the installation in both interactive and headless mode.

Host OS: Ubuntu 21.04 x64

Thanks
-Rv

```
root@ubuntu-s-1vcpu-2gb-amd-sfo3-01:~# curl -fsSL https://get.swarmlet.dev | bash -s \
  INSTALLATION_TYPE=noninteractive \
  INSTALL_ZSH=true \
  INSTALL_MODULES="matomo swarmpit" \
  NEW_HOSTNAME=swarm-manager-1 \
  SWARMLET_USERNAME=admin \

=====> Installing Swarmlet
-----> Installing required packages
-----> Cloning https://github.com/swarmlet/swarmlet.git
-----> Initializing Swarmlet
-----> Starting noninteractive installation
-----> Installing Ansible

root@ubuntu-s-1vcpu-2gb-amd-sfo3-01:~# docker
Command 'docker' not found, but can be installed with:
snap install docker     # version 19.03.13, or
apt  install docker.io  # version 20.10.2-0ubuntu2
See 'snap info docker' for additional versions.
root@ubuntu-s-1vcpu-2gb-amd-sfo3-01:~# swarm
Command 'swarm' not found, but can be installed with:
apt install swarm
```

**Comment by rvenugopal** [comment]
Installing docker and docker-compose before beginning the swarmlet headless installation resolved this issue.
Docs and (video) are out of date

**Comment by n-rodriguez** [comment]
> Installing docker and docker-compose before beginning the swarmlet headless installation resolved this issue.
> Docs and (video) are out of date

There is a PR for this : https://github.com/swarmlet/swarmlet/pull/105

to test it :

```sh
curl -fsSL https://raw.githubusercontent.com/swarmlet/swarmlet/wip/debian/install | bash -s \
  INSTALLATION_TYPE=noninteractive \
  INSTALL_MODULES="matomo swarmpit" \
  SWARMLET_USERNAME=admin \
  SWARMLET_PASSWORD=admin \
  SWARMLET_REPO=https://github.com/swarmlet/swarmlet.git \
  INSTALL_BRANCH=develop
```

**Comment by n-rodriguez** [comment]
This PR adds Kitchen/Inspec tests against Debian 10 and Ubuntu 20.04 and a Vagrantfile to run Swarmlet on your laptop.

See: https://github.com/swarmlet/swarmlet/actions/runs/850079056

Ubuntu 20 fails for an unknown reason because it works with Vagrant. Maybe we should add a new platform in https://github.com/swarmlet/swarmlet/blob/develop/kitchen.yml#L39 to test against Ubuntu 21.

**Comment by rvenugopal** [comment]
> > I just tried an installation on a digital ocean server and looks like the installation is incomplete. As per the docs docker also should have been installed. I tried the installation in both interactive and headless mode.
> > Host OS: Ubuntu 21.04 x64
> 
> There is a PR for this : #105
> 
> to test it :
> 
> ```shell
> curl -fsSL https://raw.githubusercontent.com/swarmlet/swarmlet/develop/install | bash -s \
>   INSTALLATION_TYPE=noninteractive \
>   INSTALL_MODULES="matomo swarmpit" \
>   SWARMLET_USERNAME=admin \
>   SWARMLET_PASSWORD=admin \
>   SWARMLET_REPO=https://github.com/swarmlet/swarmlet.git \
>   INSTALL_BRANCH=develop
> ```

Thank you @n-rodriguez 
I just tested it on debian 10 x64 and the docker installation did seem to go through.  However, the installation seemed to get stuck at the `deployer not (yet) healthy`.  Maybe it is just a temporary glitch?

```
 -----> Installing core/router
-----> Creating repository router on swarm
Initialized empty Git repository in /mnt/gfs/git/repo/router.git/
       Created remote repository router
/tmp/swarmlet/modules/core/router ~
Initialized empty Git repository in /tmp/swarmlet/modules/core/router/.git/
[master (root-commit) 289c210] initial
 14 files changed, 610 insertions(+)
 create mode 100644 .devcontainer/Dockerfile
 create mode 100644 .devcontainer/devcontainer.json
 create mode 100644 .env
 create mode 100644 docker-compose.yml
 create mode 100755 entrypoint
 create mode 100644 lego/.devcontainer/Dockerfile
 create mode 100644 lego/.devcontainer/devcontainer.json
 create mode 100644 lego/.gitignore
 create mode 100644 lego/Dockerfile
 create mode 100644 lego/go.mod
 create mode 100644 lego/go.sum
 create mode 100644 lego/main.go
 create mode 100644 lego/main.go_old
 create mode 100644 traefik-dynamic.yml
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Compressing objects: 100% (18/18), done.
Writing objects: 100% (19/19), 14.25 KiB | 4.75 MiB/s, done.
Total 19 (delta 1), reused 0 (delta 0)
remote: -----> Repository received
remote: -----> Cloning repository router
remote: -----> deployer not (yet) healthy
remote: -----> deployer not (yet) healthy
....
```
