### ISSUE TITLE
Using swarmlet `git push` machinery only

### ISSUE THREAD

**Issue by decentral1se** [swarmlet/swarmlet#13]
Hey, awesome project!

I already have configuration management to take care of my swarm setup and I don't need some of the applications like consul (I run a single host cluster) or matomo (not always needed).

So, I am wondering, is it possible to configure a "bare" installation of swarmlet that just assumes that the swarm is up and just has to manage the SSH connections and deploy the stacks after that?

I am not sure if that would just cause issues within the bash scripts by creating two execution paths for "bare" and "full" install but I thought I'd open a ticket to see if it is possible to do this here in the project.

**Comment by decentral1se** [comment]
Ah, I see https://swarmlet.dev/docs/getting-started/installation/#installing-swarmlet-on-a-server now and it seems like this is already possible :) Sorry for the noise :+1:

**Comment by woudsma** [comment]
Hey, thanks for your interest in the project!
That is a very valid question, and yes this is something I'd really like to do.
I actually thought about it before going to sleep yesterday.

Please re-open the issue, because this functionality is not implemented yet! :') Sorry.
My number one priority is to update the docs https://github.com/swarmlet/swarmlet/issues/11 to explain which functionality is working, and what is not.

If you care to think with me about implementation, or want to help out, please submit a PR!
They are most welcome :)

**Comment by woudsma** [comment]
Short tour:

- We would need to skip installation of Docker and Docker Compose if `SOME_VAR=true` is set.
https://github.com/swarmlet/swarmlet/blob/f07bd866a8750ddb08070e44c0014c44326b809d/install#L63-L67

- This is the part where we set up the git user.
https://github.com/swarmlet/swarmlet/blob/f07bd866a8750ddb08070e44c0014c44326b809d/src/subcommands/init#L9-L17

- If swarm mode is already initialized on an existing swarm, skip swarm mode initialization.
https://github.com/swarmlet/swarmlet/blob/f07bd866a8750ddb08070e44c0014c44326b809d/src/subcommands/init#L25-L30

- Maybe let the user choose what services will be included during installation.
  Traefik takes over all routing for example (have not looked into this), this is something we need to keep in mind.
https://github.com/swarmlet/swarmlet/blob/f07bd866a8750ddb08070e44c0014c44326b809d/src/subcommands/init#L55


I could be missing some things, but Swarmlet is actually pretty simple, it just creates an extra user (the git user) which handles incoming SSH requests, creates a repository on the server and deploys the project using the `deployments` service, which is just a container that runs every time you deploy.

These are the folders it creates:
```sh
/opt/swarmlet    # contains the code from this repo
/var/repo        # contains 'bare' git repositories
/var/repo/myproject.git    # the bare git repo for your project, doesn't contain the repo contents, it just makes it possible to push to

/home/git              # the home folder of the git user
/home/git/myproject    # a folder containing the project repo including files
/home/git/<service>    # a folder for every service included during installation, same as 'myproject', it contains https://github.com/swarmlet/swarmlet/tree/master/services/deployments for example
```

**Comment by decentral1se** [comment]
Oh, nice short tour! I already took a stab in https://github.com/swarmlet/swarmlet/pull/14 but now I see this, I will read over and think about it. Thanks for the further info.

**Comment by woudsma** [comment]
It is now possible to customize a fresh installation of Swarmlet, as can be seen here: https://vimeo.com/412918465
Now you can disable the installation of optional services such as Matomo/Swarmpit/Swarmprom/Portainer.
Unfortunately there is no functionality yet to update from an older version, this is something I'm still working on.
Closing for now! 🙂
