### ISSUE TITLE
Improve installation debugging workflow

### ISSUE THREAD

**Issue by woudsma** [swarmlet/swarmlet#18]
Let's add some functionality to easily uninstall / reinstall Swarmlet.
Something like:
```sh
uninstall-swarmlet() {
  rm -rf /opt/swarmlet
  rm -rf /var/repo
  rm -rf /home/git
  deluser git
}

reinstall-swarmlet() {
  uninstall-swarmlet
  curl -fsSL https://get.swarmlet.dev | bash
  # or install the 'develop' branch using:
  curl -fsSL https://get.staging.swarmlet.dev | bash -s INSTALL_BRANCH=develop
}
```

Idea: using [oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh) on the server could speed things up. Function name completion, history search etc. instead of pure Bash.
Think about installing zsh optionally(?):
```sh
apt-get install -y zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```

**Comment by angrynerds-andrzej** [comment]
Was about adding it by myself, so +1

**Comment by woudsma** [comment]
I'm quite busy trying to patch all the current bugs, if you want to help out and speed things up, PR's are most welcome 😉

**Comment by woudsma** [comment]
I've created https://get.staging.swarmlet.dev which points to https://raw.githubusercontent.com/swarmlet/swarmlet/develop/install

This would allow changes to the develop branch to be installed using `curl -fsSL https://get.staging.swarmlet.dev | bash`.
I still have to add some code to switch to the develop branch during installation, but that shouldn't 
be too much work. Right now this makes it easy to test the `install` script using `curl`.
Am I overthinking this workflow?

Even fancier would be `https://get.staging.swarmlet.dev/<username>` to install a forked repo.
Should be quite easy. This is the current NGINX conf for https://get.staging.swarmlet.dev:
```nginx
server {
  listen 80;
  root /var/www;

  location / {
    rewrite ^(.*)$ https://raw.githubusercontent.com/swarmlet/swarmlet/develop/install break;
  }
}

```

**Comment by awojtczyk** [comment]
It's a little overthinking, but at this stage it will be helpfull.
