### ISSUE TITLE
Use Conventional Commits for contributions?

### ISSUE THREAD

**Issue by woudsma** [swarmlet/swarmlet#19]
https://www.conventionalcommits.org/en/v1.0.0/

I'm thinking about using [`cz-cli`](https://github.com/commitizen/cz-cli).
The downside is that it requires adding a `package.json` and `package-lock.json` to the project, and requires `npm` or `npx` to be installed in order to consistently use Conventional Commits.

I haven't found good lightweight alternatives which are more language-agnostic.
Let me know if you have suggestions!

**Comment by awojtczyk** [comment]
Let's set it up once we have stable version with all core functionalities implemented.
