### ISSUE TITLE
Upgrade to Traefik 2.0 for easier Let's Encrypt wildcard certificates

### ISSUE THREAD

**Issue by woudsma** [swarmlet/swarmlet#2]
Notes:
- https://docs.traefik.io
- https://medium.com/@containeroo/traefik-2-0-wildcard-lets-encrypt-certificates-1658370adc68
- https://frankw.net/traefik-2-0-upgrade-with-docker-compose/
- https://moritzvd.com/upgrade-traefik-2/

**Comment by awojtczyk** [comment]
I'm taking this point for myself, it should be ready around the. weekend.

**Comment by woudsma** [comment]
That would be awesome, keep me up to date!
