### ISSUE TITLE
Managing cluster configuration and application secrets

### ISSUE THREAD

**Issue by woudsma** [swarmlet/swarmlet#26]
I'd like to be able to store my cluster configuration in a central location, I'm thinking of using a `config` service, which you can clone/pull/edit/push like any other service you've deployed. If the `config` service is updated, all apps using this configuration have to be updated as well.

App-specific secrets should not be stored in the `config` service, I'd like to store them in a safe location by creating a `vault` service for example. I'm currently looking into HashiCorp Vault + Consul, since Traefik integrates nicely with Consul already. Vault would provide a web UI, this is where application secrets (S3/API/SSH keys) can be stored on the swarm itself.

The `deployer` service will need access to the vault to use secrets in the stack build phase, that should be possible.

[`add-vault`](https://github.com/swarmlet/swarmlet/tree/add-vault) branch.

Notes:
https://www.marcolancini.it/2017/blog-vault/
https://learn.hashicorp.com/vault/getting-started/ui
https://testdriven.io/blog/managing-secrets-with-vault-and-consul/

**Comment by decentral1se** [comment]
`docker config` is the way to go indeed.

For secrets management, I would suggest using `docker secret`. Using the Docker-compose 3.8 schema, there is full integration. You just put `{{ secret "mysecret" }}` in your config and use `template_driver: golang` on your compose secret definition and it will work! You load secrets into the swarm using `docker secret create`. 

This would avoid an additional service in the swarm. I guess both approaches are valid so again it is a question of how the end-user wants to manage their swarm which is somewhat being decided for them if you integrate vault of docker secret anyway :question: 

See examples in the following:
- https://git.autonomic.zone/autonomic-cooperative/traefik/src/branch/master/docker-compose.production.yml#L73
- https://git.autonomic.zone/autonomic-cooperative/traefik/src/branch/master/configs/prod/forward.ini.tmpl
- https://git.autonomic.zone/autonomic-cooperative/traefik/src/branch/master/requirements.txt

**Comment by woudsma** [comment]
This looks promising. Thanks for your input!
Also a good example of a Traefik v2 setup! That could help https://github.com/swarmlet/swarmlet/issues/2

Valid point about choosing for the end user. I'm all for staying as close to Docker as possible.
The only thing I want to avoid is the Dokku-like style of entering secrets, needing to SSH into the server to change some variable. The thing I liked about Vault was it's single purpose and good web interface. The Gitlab way of storing secrets is perfect IMO. But self-hosting Gitlab CE is quite resource-intensive. Maybe we can find a solid go-to UI, where you can configure swarm settings (the root domain, access control, registry settings?, etc) and secrets for individual applications. Using `docker secret` and `docker config` under the hood instead of Vault for example.

Entering secrets using the docker CLI would still be possible of course. Including an UI would be optional for example. Portainer and Swarmpit are good candidates but I should probably do some further research. Suggestions welcome!

**Comment by decentral1se** [comment]
> The only thing I want to avoid is the Dokku-like style of entering secrets, needing to SSH into the server to change some variable.

Yeah true, that sucks. To do that with the docker CLI, you need to setup TLS encrypted remote docker API communcations and that is a bitttt annoying the first time around, see https://docs.docker.com/engine/security/https/. Perhaps swarmlet could take care of the secrets generation via https://github.com/paulczar/omgwtfssl (makes it a no-brainer).

> Valid point about choosing for the end user. I'm all for staying as close to Docker as possible.

That's my intuition on the default. I like the idea that swarmlet can easily accomodate other workflows (using consul, vault, etc.) and supporting those from the swarmlet "core" (meaning, you guarantee that you maintain some configs for those compose files) is a good idea TM. I'm working on a plain single host cluster so that is my bias :)
