### ISSUE TITLE
Updating an existing installation

### ISSUE THREAD

**Issue by gnovotny** [swarmlet/swarmlet#38]
Do you have any pointers for updating an existing installation? My version is pre-v0.1

**Comment by woudsma** [comment]
Not yet, this is something I'm definitely planning to do for v0.3.
We've almost finished v0.2 (https://github.com/orgs/swarmlet/projects/4).

Feedback and/or contributions are always welcome!

**Comment by woudsma** [comment]
Updating Swarmlet is now as simple as running `swarmlet update` on the swarm manager!
This version is not backwards compatible with pre-v0.2.9 versions though, so you would need to set up things from scratch.
