### ISSUE TITLE
Shared persistent storage/volume solution

### ISSUE THREAD

**Issue by woudsma** [swarmlet/swarmlet#53]
Before upgrading to Traefik v2.0+ we need to find a way to store the Let's Encrypt certificates, since Traefik doesn't support Consul as a distributed key/value store anymore.

I'm looking for a good solution to store certificates across the swarm so that they're always available and up-to-date.

Currently looking at:
https://awesome-docker.netlify.app/#volume-management--data
https://github.com/rexray/rexray
https://github.com/minio/minio
https://github.com/MatchbookLab/local-persist
https://sysadmins.co.za/docker-swarm-persistent-storage-with-nfs/

**Comment by chumpyy** [comment]
Another option to consider would be a distributed storage solution (GlusterFS) with replication on all traefik nodes. I have only recently set this up manually for testing so can't really comment on the long term reliability, automatizing the setup or monitoring the health of replication sets. But so far so good, replication works and GlusterFS seems light on the resource consumption side of things.

I didn't use this tutorial, but it gives you an idea:
https://thenewstack.io/tutorial-create-a-docker-swarm-with-persistent-storage-using-glusterfs/

**Comment by woudsma** [comment]
Thanks for the feedback! For some reason I didn't see GlusterFS yet, it looks promising!
I was looking into [Storidge](https://docs.storidge.com/docker_volumes/overview.html#abstraction-layer) as well, but after diving a little deeper that seemed overkill (especially the resource requirements).

Something secure + lightweight would be awesome. 
I'm going to look into GlusterFS asap 🙂

**Comment by fishnux** [comment]
@woudsma has implemented GlusterFS on the feature/glusterfs branch. However, I believe the Gluster setup commands need to be revised to use a "Replicated Glusterfs Volume" instead of the default "Distributed Glusterfs Volume":
https://docs.gluster.org/en/latest/Quick-Start-Guide/Architecture/

The addition/removal of nodes is still being worked on as far as I'm aware.

(For the record, I'm not working on this issue)

**Comment by woudsma** [comment]
Note to self: look into using Ansible to manage GlusterFS
https://docs.ansible.com/ansible/latest/index.html
