### ISSUE TITLE
Installation error with Ubuntu18.04 on Vultr

### ISSUE THREAD

**Issue by sardaukar** [swarmlet/swarmlet#6]
I spawned a new server on Vultr, ran the installer and it halted with an error:

```
-----> Selecting network interface
Device "eth1" does not exist.
eth0: error fetching interface information: Device not found
```

**Comment by sardaukar** [comment]
This is the output of `ip addr show` after erroring out of the installer

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 56:00:02:b9:76:aa brd ff:ff:ff:ff:ff:ff
    inet <IP>/23 brd <IP> scope global dynamic ens3
       valid_lft 86287sec preferred_lft 86287sec
    inet6 <IP>/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 2591888sec preferred_lft 604688sec
    inet6 <IP>/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:8b:85:dd:84 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by woudsma** [comment]
Yeah.. So there is no network device named eth0 or eth1.
I've hardcoded these as the only 2 options for grabbing the IP address of the VPS.
I'm on DigitalOcean, I guess things are different at Vultr.

This is where I'm getting the IP address:
https://github.com/swarmlet/swarmlet/blob/master/src/subcommands/init#L25

I would have to look into getting the server IP address in a different way.
I'm not going to be able to fix this issue before the weekend.

You could also just fork the project, use a different method of finding the IP address and change this line:
https://github.com/swarmlet/swarmlet/blob/master/src/subcommands/init#L31
If you fix it yourself, please help me by creating a pull request :)
Thanks!

**Comment by woudsma** [comment]
If you fork the repo, you should also change this line to use your repo fork url:
https://github.com/swarmlet/swarmlet/blob/master/install#L26

Then you can install Swarmlet using
```sh
curl -fsSL https://raw.githubusercontent.com/YOURNAME/swarmlet/master/install | bash
```

**Comment by sardaukar** [comment]
Made a PR #7

**Comment by sardaukar** [comment]
Oh just saw your comment on how to test this, will try on a Vultr instance!
