### ISSUE TITLE
Duplicate Key in registry Docker-Compose

### ISSUE THREAD

**Issue by corepay** [swarmlet/swarmlet#83]
FYI: placement key is duplicate in docker-compose.yaml

https://github.com/swarmlet/swarmlet/blob/6d57e9dfb6e42276cbf67a36decdc57881aee716/modules/core/registry/docker-compose.yml#L33

![image](https://user-images.githubusercontent.com/48992923/100498602-cac90280-3139-11eb-957b-f9ffd2550b41.png)

**Comment by woudsma** [comment]
Thanks! Will look into it
