### ISSUE TITLE
Stacks are not redeployed when pushing to existing repositories

### ISSUE THREAD

**Issue by woudsma** [swarmlet/swarmlet#85]
Quoting a user from the Swarmlet Slack channel:
> I'm on the latest release of swarmlet
when I push to existing repositories, the swarm stacks / services are not redeployed for some reason
I always have to delete the stack before pushing
I solved this by adding --with-registry-auth --resolve-image always  to docker stack deploy  in the deployer entrypoint file

**Comment by n-rodriguez** [comment]
Same here. Killing the container after redeploy is sufficient  to use the latest image but it's definitely a bug.

**Comment by awojtczyk** [comment]
@n-rodriguez are you up to provide some solution for this?

**Comment by n-rodriguez** [comment]
@awojtczyk I confirm that this fix work : https://github.com/n-rodriguez/swarmlet/commit/c2759e492585e641b7bb6608e77602b3875720f5

**Comment by awojtczyk** [comment]
Thanks! @n-rodriguez
