### ISSUE TITLE
How to access swarmpit?

### ISSUE THREAD

**Issue by sardaukar** [swarmlet/swarmlet#9]
I installed swarmlet on a domain, but can't seem to get anything but 404s. Should swarmpit be accessible from swarmpit.domain.tld?

**Comment by sardaukar** [comment]
Also, `swarmlet info` tells me `unknown command`. Is that a known issue?

**Comment by woudsma** [comment]
Yeah, at this stage there are some things not implemented, such as `swarmlet info`.
Sorry 😅 I have to update the docs.

Also to deploy a service to the web, you need to pull, change the URL in the `.env` file, and push again to redeploy and configure services included by Swarmlet (Matamo and Swarmpit atm).

**Comment by woudsma** [comment]
* Try to pull the Swarmpit repo from the swarm using `git clone git@swarm:swarmpit`, edit and `git push origin master`.

**Comment by sardaukar** [comment]
I think the hostname setting probably has an issue. I see

```
remote: =====> Stack deployed:
remote: [swarmpit] — https://swarmpit./home/git/swarmpit
```

the `$HOSTNAME` is set to the proper value, though.

**Comment by woudsma** [comment]
@sardaukar Exactly, and I'm not sure why `$HOSTNAME` is not displayed. Probably because the deployments service runs the build in a Docker container and doesn't have a hostname. In any case you should define the domain name in the `.env` file of any web service - at the moment.

This workflow should also be improved and explained in the docs. If you feel like helping out, please do! 👍

**Comment by sardaukar** [comment]
I'll have a look at this tomorrow! Thanks

**Comment by woudsma** [comment]
I'm curious if you've managed to host Swarmpit on your domain yet using Swarmlet.
Let me know when you do! 😃 

Later today I'm going to update the docs on how to configure Swarmpit, Matomo and optionally Swarmprom/Portainer.

**Comment by sardaukar** [comment]
Yeah, I'm curious about that too. It'd be great to just work out of the box.

**Comment by woudsma** [comment]
100% agree.
Have you tried these steps?
```sh
# on your local machine

git clone git@swarm:swarmpit
cd swarmpit
nano .env  # edit DOMAIN=swarmlet.dev to your domain
git add . && git commit -m 'update'
git push origin master
```
If the service is not accessible online after a few minutes, you could try following the logs of both Swarmpit and Traefik if you can find any clues.
```sh
# on the server

docker service logs swarmpit_app -f
docker service logs loadbalancer_traefik -f
```

**Comment by woudsma** [comment]
I've just updated the master branch with some fixes, setting a root domain during installation should fix this issue. You can try it using:
```sh
curl -fsSL https://get.swarmlet.dev | bash -s ROOT_DOMAIN=dev.mydomain.com
```
(assuming `*.dev.mydomain.com` is pointed to the server you're installing Swarmlet on).

This should make these domains accessible after installation:
```
https://swarmpit.dev.mydomain.com
https://matomo.dev.mydomain.com
https://traefik.dev.mydomain.com
https://consul.dev.mydomain.com
```

Please let me know if you get the chance to try it out!

**Comment by woudsma** [comment]
Closing this for now, please re-open if you are still running into this issue after a fresh installation.

**Comment by sardaukar** [comment]
Hey sorry have been busy lately, will check this out soon!
